### ISSUE TITLE
Next-intl + SSG in build mode, interception routing does not work properly

### ISSUE THREAD

**Issue by daofeng-1998** [amannn/next-intl#642] opened 2023-11-17 14:23 UTC
### Description

Next-intl + SSG is used. In dev mode, interception routing works normally, but not in build mode.
Node: 18.11.0

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/daofeng-1998/next-intl-intercepting-route-issue

### Reproduction description

Steps to reproduce:
1. Open reproduction && pnpm i && pnpm run build && pnpm run start
2. Click on Go Func -> Click on Login
3. See error: 

### Expected behaviour

Expect it to work

**Comment by amannn** [comment] 2023-11-17 14:33
This might be a duplicate of https://github.com/amannn/next-intl/issues/255. Parallel and intercepted routes currently have some rough edges as far as I know. I'm unfortunately not aware of anything that can currently be fixed on the `next-intl` side.

**Comment by louisthomaspro** [comment] 2023-11-22 08:09
@amannn is it also the cause of:
`You cannot have two parallel pages that resolve to the same path. Please check /[locale]/(main)/@modal/(.)album/[id]/quickview/page and /[locale]/[...rest]/page. Refer to the route group docs for more information: https://nextjs.org/docs/app/building-your-application/routing/route-groups` ?

**Comment by amannn** [comment] 2023-11-23 11:12
@louisthomaspro Not sure to be honest! I haven't used parallel routes so far since users have reported upstream issues on the Next.js side.

I'll close this as a duplicate of #255.

**Closed by amannn** 2023-11-23 11:12 UTC
Labels: bug, unconfirmed
