### ISSUE TITLE
Changing language unmounts the component tree

### ISSUE THREAD

**Issue by ChezFre** [amannn/next-intl#863] opened 2024-02-15 10:29 UTC
### Description

When the language is updated via `router.replace(pathname, { locale })` or the `Link` `locale` prop as described [in the docs](https://next-intl-docs.vercel.app/docs/routing/navigation#userouter) the component tree gets remounted. This causes every child component to  reset its internal state.

### Mandatory reproduction URL

https://codesandbox.io/p/github/ChezFre/next-intl-rerender-isssue/

### Reproduction description

Steps to reproduce:
1. Click on the count button to increase the local state of the client component
2. Click on the navigation link of the inactive page
3. Notice that the count value has remained the same
4. Click on the language button or link of the inactive language
5. Notice that the count has reset to 0

### Expected behaviour

Changing the language should not unmount the component tree.

**Comment by amannn** [comment] 2024-02-15 13:16
This is a duplicate of https://github.com/amannn/next-intl/discussions/723.

**Closed by amannn** 2024-02-15 13:16 UTC
Labels: bug, unconfirmed
