### ISSUE TITLE
next-intl/plugin doesn't working with next 13 with app directory

### ISSUE THREAD

**Issue by destery** [amannn/next-intl#399] opened 2023-07-12 16:53 UTC
### Description

i use this code in my next config
const withNextIntl = require('next-intl/plugin')(
    // This is the default (also the `src` folder is supported out of the box)
    './i18n.js'
);
And start the project with turbopack
When i load some page i get error
(Logs)
<img width="1688" alt="изображение" src="https://github.com/amannn/next-intl/assets/71778165/c2e3d065-378b-4165-a880-a06ab80f1b05">
<img width="1680" alt="изображение" src="https://github.com/amannn/next-intl/assets/71778165/38429c73-7907-45b2-ae8f-4126e71f13ca">
<img width="1688" alt="изображение" src="https://github.com/amannn/next-intl/assets/71778165/0aeefc4c-0685-4eb8-8f44-639a3f0ec84e">

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

mkjnjnjmk

### Reproduction description

Steps to reproduce:
1. Launch project with your next-config and turbopack!
2. Check the logs.

### Expected behaviour

i expect that it will work

**Comment by amannn** [comment] 2023-07-13 07:21
Duplicate of https://github.com/amannn/next-intl/issues/250

**Closed by amannn** 2023-07-13 07:21 UTC
Labels: bug, unconfirmed
