### ISSUE TITLE
useTranslations support for async rsc

### ISSUE THREAD

**Issue by ddenizakpinar** [amannn/next-intl#406] opened 2023-07-15 12:43 UTC
### Is your feature request related to a problem? Please describe.

Currently `useTranslations` works fine with server components but when I convert the component to async it throws 
`Error: Expected a suspended thenable. This is a bug in React. Please file an issue.`.
Will there be a support for this situation?

### Describe the solution you'd like

It should work as it is working on sync rsc

**Comment by StevenLangbroek** [comment] 2023-07-19 15:21
Hey @ddenizakpinar! This issue is closed as "completed", but I'm still getting this error with latest `next` + `next-intl`...

**Comment by bastienrobert** [comment] 2023-09-28 09:22
> Removing async from the component fixed it for me.

ref. https://github.com/vercel/next.js/issues/51477#issuecomment-1605668532
ref. https://github.com/vercel/next.js/issues/51477#issuecomment-1620257445

**Comment by rentalhost** [comment] 2023-10-05 23:24
@ddenizakpinar can you please reopen this issue? I need use `async` anyway, and I am hitting this issue on `3.0.0-rc.2`.

**Comment by ddenizakpinar** [comment] 2023-10-11 21:03
@rentalhost done

**Comment by amannn** [comment] 2023-10-12 07:38
This issue was discussed at length here: https://github.com/amannn/next-intl/discussions/276

Does the mentioned workaround in the error message work for you?

**Comment by AliothNg** [comment] 2023-10-13 01:42
> This issue was discussed at length here: #276
> 
> Does the mentioned workaround in the error message work for you?

I think it's about the fact that the use() api is only available in experimental and canary channels.I am using

react 18.2.0
next-intl 3.0.0-rc.4
next 13.5.4
After manually enable the experiemental flag ppr:true in next.config.mjs, useTransitions() in async rsc works

**Comment by AliothNg** [comment] 2023-10-13 02:06
I just find out that `useFormat()` still dosen't work

**Comment by amannn** [comment] 2023-10-14 12:06
> After manually enable the experiemental flag ppr:true in next.config.mjs, useTransitions() in async rsc works

Really? I couldn't reproduce this with the latest `next` version.

**Comment by AliothNg** [comment] 2023-10-14 18:16
> > After manually enable the experiemental flag ppr:true in next.config.mjs, useTransitions() in async rsc works
> 
> Really? I couldn't reproduce this with the latest `next` version.

Sorry, it's my fault. I double examined the code and confirmed I was wrong.
Meanwhile, i did some digging. The problems comes from the use() call in an async RSC. It's not implemented yet and should be considered as an error. Comments can be found here.[Link to the comment](https://github.com/vercel/next.js/issues/42469#issuecomment-1303615628).
The problems has been there for nearly a year and I don't think there's any progress .So maybe we can export an  async version for useTranslations say useTranslationsAsync without using the use() api  as a workaround. I believe this won't cost too much effort.

**Comment by amannn** [comment] 2023-10-19 13:25
After writing the [detailed comment above](https://github.com/amannn/next-intl/issues/406#issuecomment-1759094798) I gave the topic of the function signature of `t.rich` some more thought. I think previously this was somewhat confusing, since `t.rich` would either operate on React elements or strings depending on if you receive the function from `useTranslations` or `getTranslator`.

Based on this, the latest 3.0 release candidate `next-intl@3.0.0-rc.6` now includes a new `t.markup` function that removes this ambiguity. By doing this, `(await getTranslator(locale)).rich` will now return a `ReactNode` and can be used for edge cases of server-only components. See also [the release notes](https://next-intl-docs.vercel.app/blog/next-intl-3-0).

The general recommendation is still to split components, as this will naturally result in the creation of shared components that work in either environment.

I think based on this, this issue can be closed. Hope this helps!

**Closed by amannn** 2023-10-19 13:25 UTC
Labels: enhancement, unconfirmed
