### ISSUE TITLE
Publish version of use-intl

### ISSUE THREAD

**Issue by Industrial** [amannn/next-intl#38] opened 2021-06-16 12:04 UTC
**Describe the bug**
The latest version used by next-intl isn't published but is available in git

**To Reproduce**
`yarn add next-intl` asks for a version of `use-intl` because the one used in `next-intl` isn't available

**Comment by amannn** [comment] 2021-06-16 12:07
Thanks for the report! I believe this is a duplicate of https://github.com/amannn/next-intl/issues/37, which should be fixed nows. Can you confirm that?

**Closed** 2021-06-16 12:18 UTC
Labels: bug
