### ISSUE TITLE
Can I use next-intl in Next.js app router, but not rely on the locale in the path？

### ISSUE THREAD

**Issue by EryouHao** [amannn/next-intl#490] opened 2023-08-31 02:02 UTC
### Is your feature request related to a problem? Please describe.

I'd like to use next-intl, but I don't want to utilize Next.js's [locale] routing mechanism, as SEO is not particularly important to me. Instead, I prefer to have a single path that allows access to pages in multiple languages, such as using the user's custom-selected language or browser preferences for displaying localized content.

My current live webpage is set up this way, with a language-switching button in the top right corner.

https://gridea.dev

However, I'm unsure how to use next-intl within the Next.js 13 app router mechanism. Could you please provide some assistance on this matter?

### Describe the solution you'd like

The folder I expect is written as follows:

<img width="1198" alt="image" src="https://github.com/amannn/next-intl/assets/17328747/ad483645-16c2-43ef-9f07-e913f29628e1">

### Describe alternatives you've considered

Not yet, but I still hope to use next-intl to solve this problem.

**Comment by amannn** [comment] 2023-08-31 06:21
Duplicate of https://github.com/amannn/next-intl/issues/366

**Closed by amannn** 2023-08-31 06:21 UTC
Labels: enhancement, unconfirmed
