### ISSUE TITLE
It doesnt work with turbopack

### ISSUE THREAD

**Issue by mag-nikita-ks** [amannn/next-intl#740] opened 2023-12-20 08:52 UTC
### Description

When using turbopack it doesnt work with different locales, in my case it supports only de and en locals

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/amannn/next-intl/tree/main/examples/example-app-router

### Reproduction description

start example project with app router
add next dev --turbo
add local fr.json or it.json or uk.json
change related files to support selected locales and run project

### Expected behaviour

It should use selected locale.json file

**Comment by amannn** [comment] 2023-12-21 09:45
This looks like a duplicate of this: https://github.com/amannn/next-intl/issues/718#issuecomment-1856252053

Turbopack support is currently experimental. If you want to help here, you can report this bug upstream in the Turbopack repo (in case it hasn't already been reported).

**Closed by amannn** 2023-12-21 09:45 UTC
Labels: bug, unconfirmed

**Comment by Audrey-Ann** [comment] 2023-12-27 18:55
Hey @amannn I don't know if this can help or give more context but I open this discussion in NextJS Github community: 

https://github.com/vercel/next.js/discussions/59720

I think the main raison why it's not working with Turbo (at least with my setup) is because when turbo cannot find the `middleware.ts` which contains the configuration for localization. 

What are your thoughts? 

(Happy holidays as well!)

**Comment by amannn** [comment] 2023-12-28 08:20
From my experience, the middleware compiles just fine. You're right that the log output doesn't mention the middleware though (not sure if intended).

Happy holidays!

**Comment by Audrey-Ann** [comment] 2023-12-28 15:50
@amannn thank you for your quick response! 

That’s good to know, but could you, when the time permits, share your setup please (similarly like how I shared mine in the nextjs discussion)? 

I might be missing something…? I really tried everything by now and I’m kinda starting to feel hopeless 😞. In my case, it gets stuck and no pages are being loaded successfully when using turbo…

I am now on the latest version of nextjs canary + next-intl (3.4.0) + Typescript v5 and still no luck… 🍀 

Addionaly, it would be very appreciated if a boilerplate/example with turbo support could be added to the github’s examples or documentation. I’m positive it will help many!

Thank you very much! Sending you positive vibes and looking forward to your reply ~ 🙂

**Comment by amannn** [comment] 2023-12-29 07:04
[The App Router example](https://next-intl-docs.vercel.app/examples#app-router) can be started with `--turbo`. Maybe that helps! It's quite a minimal example at this point but illustrates that `next-intl` works with Turbo.

I'm personally not using Turbo for commercial projects yet due to other bugs in Turbo I've encountered. I therefore don't recommend using it currently and the support in `next-intl` is considered experimental. I think for now we might have to wait for the Turbo team to iron out the current issues :).

**Comment by Audrey-Ann** [comment] 2023-12-29 16:39
Thank you very much @amannn, I'll checkout this [App Router example](https://github.com/amannn/next-intl/tree/main/examples/example-app-router) and compare it with my setup. 

However like you mentioned, I think I will wait as well before spending more time on this since it is considered experimental with Turbo. Hopefully the latest official releases of NextJS 14 will improve the Turbo experience and setup!

Have a pleasant rest of your day! Again thank you for your contribution! 🙂

**Comment by mifrej** [comment] 2024-02-29 12:28
The example you point to @amannn when using with `--turbo` flag is not working.
The page remains fixed on one translation only, when with --turbo, whatever route language segment you use.

So bottom line is next-intl does not work with Turbo, but I get the point of --turbo being experimental, just wanted to clarify this here

**Comment by amannn** [comment] 2024-02-29 13:11
@mifrej There was a recent discussion about this in https://github.com/amannn/next-intl/issues/898 and it seems like there's movement on the Turbo side in regard to this 🤞

**Comment by kevinrss01** [comment] 2025-01-03 13:01
Same issue here
