### ISSUE TITLE
Typescript type for values provided to a message

### ISSUE THREAD

**Issue by einarlove** [amannn/next-intl#886] opened 2024-02-26 13:29 UTC
### Is your feature request related to a problem? Please describe.

**Given this example:**

```javascript
import { createTranslator } from "next-intl";

const messages = {
  basic: "Hello {name}!",
};

const t = createTranslator({ locale: "en", messages });

t("basic", { name: "world" }) // -> Hello world!
t("basic", { whatever: "world" }) // basic
```

It gives no error. I would want the values `TranslationValues` to be typed so that I can't pass anything, undefined or nothing at all.
The ICU message syntax does not allow optional values—as in render something else if no value—, so the translation function should not accept empty values.

### Describe the solution you'd like

`IntlMessages` should know which values are included in the translated string and require them. Unsure of the complexity if it accept dates and the like, but a `string | number` should be good enough.

### Describe alternatives you've considered

I want typescript error for the developer to catch the mistake, and the build to fail. So I've seen no solution for this.

**Comment by amannn** [comment] 2024-02-26 13:31
Yep, I agree this would be helpful. This is a duplicate of #410.

**Closed by amannn** 2024-02-26 13:31 UTC
Labels: enhancement, unconfirmed
