### ISSUE TITLE
react-server: throws an exception when using `use`

### ISSUE THREAD

**Issue by ovflowd** [amannn/next-intl#614] opened 2023-11-09 13:43 UTC
### Description

I suspect [this](https://github.com/amannn/next-intl/blob/feat/next-13-rsc/packages/next-intl/src/react-server/useHook.tsx#L8) line of code is throwing unhandled exceptions from the `use` method.

**At least our Sentry is giving this:**

<img width="1123" alt="image" src="https://github.com/amannn/next-intl/assets/12037269/28c8261b-f9ff-494d-952f-78c3bcae5c38">

And I suspect this might be on the middleware or somewhere. I of course, have no idea where exactly on your code, but hey, might be fun to investigate.

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://github.com/nodejs/nodejs.org

### Reproduction description

1. Navigate to `/`
2. Apparently the Error is suppressed, so you can't see them anywhere (console logs, etc) but Sentry is capturing them, so I suspect this should be handled differently.

I also see no documentation on `react.dev` around `use`, what is it and what it does?

### Expected behaviour

No Exceptions

**Comment by amannn** [comment] 2023-11-09 16:53
Here are the docs for [use](https://react.dev/reference/react/use).

Earlier this week, I've improved the docs for the RSC integration, this might help to provide some context: [Using internationalization in Server Components](https://next-intl-docs-git-feat-next-13-rsc-next-intl.vercel.app/docs/environments/server-client-components#using-internationalization-in-server-components)

Generally, you can pick between an async and a hooks-based API, based on if you use APIs from `next-intl` in async or shared components (the latter allows to use non-stateful hooks, like `useId`—and also `useTranslations`).

The code snippet you've linked to points to error handling I've added, back when React/Next.js didn't explain much when a user tries to accidentally use hooks in an async component. The error message [still isn't great](https://codesandbox.io/p/sandbox/serene-blackwell-hyc2xz?file=%2Fapp%2Fpage.tsx%3A1%2C1), but at least the React ESLint plugin shows an error now:

<img width="527" alt="Screenshot 2023-11-09 at 17 48 29" src="https://github.com/amannn/next-intl/assets/4038316/0c905381-e500-4242-a10c-d17b46e1e617">

Due to this, we could consider removing the custom error handling now, but I'm wondering if Sentry would catch the promises that React/Next.js throws for various APIs like `use`, `redirect` etc. anyway. Maybe there's something to adapt on the Sentry side.

**Comment by ovflowd** [comment] 2023-11-09 17:23
> Here are the docs for [use](https://react.dev/reference/react/use).
> 
> 
> 
> Earlier this week, I've improved the docs for the RSC integration, this might help to provide some context: [Using internationalization in Server Components](https://next-intl-docs-git-feat-next-13-rsc-next-intl.vercel.app/docs/environments/server-client-components#using-internationalization-in-server-components)
> 
> 
> 
> Generally, you can pick between an async and a hooks-based API, based on if you use APIs from `next-intl` in async or shared components (the latter allows to use non-stateful hooks, like `useId`—and also `useTranslations`).
> 
> 
> 
> The code snippet you've linked to points to error handling I've added, back when React/Next.js didn't explain much when a user tries to accidentally use hooks in an async component. The error message [still isn't great](https://codesandbox.io/p/sandbox/serene-blackwell-hyc2xz?file=%2Fapp%2Fpage.tsx%3A1%2C1), but at least the React ESLint plugin shows an error now:
> 
> 
> 
> <img width="527" alt="Screenshot 2023-11-09 at 17 48 29" src="https://github.com/amannn/next-intl/assets/4038316/0c905381-e500-4242-a10c-d17b46e1e617">
> 
> 
> 
> Due to this, we could consider removing the custom error handling now, but I'm wondering if Sentry would catch the promises that React/Next.js throws for various APIs like `use`, `redirect` etc. anyway. Maybe there's something to adapt on the Sentry side.

It's worth trying imo. If you feel compelled to try :)

**Comment by ovflowd** [comment] 2023-11-23 19:35
Hey @amannn just checking in if there's anything you can check here? Our Sentry is accumulating a few thousands of "errors" because of that. Even tho these users never reach the user.

**Comment by amannn** [comment] 2023-11-24 11:11
It would be important to isolate the cause of the "errors" you're seeing in Sentry.

React throws promises in the implementation of `use`, that's the way it works and should not be considered an error.

This is the error message you're seeing:

<img width="1762" alt="Screenshot 2023-11-24 at 12 03 32" src="https://github.com/amannn/next-intl/assets/4038316/54ae45a4-174e-4e61-9b65-57e3863a86b4">

Rethrowing the error is what `next-intl` does, therefore we're in line with the suggestion.

I don't know how the Node.js integration for Sentry works, but I'm wondering if something needs to be adapted on their side.

This could be a simple reduced snippet to test:

```tsx
import {use} from 'react';

const promise = Promise.resolve('Hello');

function Test() {
 return use(promise);
}
```

If this is also reported by Sentry during an RSC render or SSR, then you might want to report this on the Sentry side.

**Comment by ovflowd** [comment] 2023-11-24 11:53
> It would be important to isolate the cause of the "errors" you're seeing in Sentry.

The errors are coming from `next-intl` more specifically your `useHook` file that wraps the server-side hooks with `try/catch` on the `use` statement

**Comment by ovflowd** [comment] 2023-11-24 11:54
> I don't know how the Node.js integration for Sentry works, but I'm wondering if something needs to be adapted on their side.

Using the Next.js one.

**Comment by ovflowd** [comment] 2023-11-24 11:57
I'm making a change, I have the feeling this might be happening on a specific root level not-found. I've changed both the root layout and not-found page to be on `/[locale]/` level, let's see what this does.

**Comment by ovflowd** [comment] 2023-11-24 14:54
> If this is also reported by Sentry during an RSC render or SSR, then you might want to report this on the Sentry side.

As you can see on the first screenshot, it's happening on a server component. And apparently still ongoing. I'm still investigating but I really can't see anything wrong on my side.

**Comment by amannn** [comment] 2023-11-25 11:05
> I'm still investigating but I really can't see anything wrong on my side.

I also don't think you're doing anything wrong, but neither do I think `next-intl` does.

If you're interested in solving this, I'd suggest you to try to create a minimal reproduction using [the snippet I've mentioned](https://github.com/amannn/next-intl/issues/614#issuecomment-1825517808) and if this triggers Sentry, then this should be reported on their side. There's nothing that `next-intl` can do to improve the situation for you if this is the case.

If we find that the issue is _caused_ by `next-intl`, then I'm happy to look into it, but we're missing an isolated reproduction that shows the root cause currently.

**Comment by ovflowd** [comment] 2023-11-25 14:28
> If you're interested in solving this, I'd suggest you to try to create a minimal reproduction using https://github.com/amannn/next-intl/issues/614#issuecomment-1825517808 and if this triggers Sentry, then this should be reported on their side. There's nothing that next-intl can do to improve the situation for you if this is the case.

I'm not sure how it makes sense to report this to Sentry. I genuinely this is happening because `useHook` surrounds a `try/catch` on the `use` statement, and this error is being triggered by React itself, which says that you shouldn't wrap `use` with `try/catch`... Isn't this the issue?

**Comment by ovflowd** [comment] 2023-11-25 14:29
> If we find that the issue is caused by next-intl, then I'm happy to look into it, but we're missing an isolated reproduction that shows the root cause currently.

Yeah, I can try that, but I wonder where to add this and where to test this... Where are you imagining that I should add this?

**Comment by ovflowd** [comment] 2023-11-25 14:35
> Rethrowing the error is what next-intl does, therefore we're in line with the suggestion.

https://react.dev/reference/react/use#suspense-exception-error by the docs here It feels that `.catch()` should be used and then rethrow the error? I might be misunderstanding here, but IO don't think it hurts to test a patched version of `next-intl` that does a different behaviour. It'd be more than happy to test a specific "patch" containing this change.

> If this is also reported by Sentry during an RSC render or SSR, then you might want to report this on the Sentry side.

I don't think that snippet would throw any error, as the Promise is always resolving.

**Comment by ovflowd** [comment] 2023-11-25 14:36
It's also written here that `use` should not be used within a `try/catch` block: https://react.dev/reference/react/use#dealing-with-rejected-promises

**Comment by ovflowd** [comment] 2023-11-25 14:38
(I apologize if I'm annoying you with this issue) but I genuinely believe that `next-intl` is implementing `use` erroneously. And I honestly feel that it's worth a shot.

**Comment by amannn** [comment] 2023-11-25 16:06
> IO don't think it hurts to test a patched version of `next-intl` that does a different behaviour.

Sure, you can use [`patch-package`](https://www.npmjs.com/package/patch-package) and modify [`next-intl/dist/esm/react-server/useHook.js`](https://unpkg.com/browse/next-intl@3.1.4/dist/esm/react-server/useHook.js) accordingly in your code base (the ESM build is used for the `react-server` condition).

Let me know if that makes a difference!

**Comment by ovflowd** [comment] 2023-11-27 11:44
Interesting, with further investigation, I was able to replicate this issue with the patch.

Apparently it happens only on Not-Found pages (404)... I need to investigate more, but I have no idea why Vercel 404's would be causing this.

**Comment by ovflowd** [comment] 2023-11-27 12:02
Okay, diving deeper. By making the `not-found` page client-only (`use-client`) the issue has resolved.

I have the feeling that Next.js was trying to render this Not Found page (that uses our Locale Layout (`/[locale]/layout.tsx`) and probably something in between was not working correctly.

Could be the middleware, or the way that Next.js would actually skip the dynamic segment, or the context of `unstable_setRequestLocale` would be lost... Who knows.

We can close this issue. The outcome here would be: Probably when using `next-intl` to make `not-found` pages use `"use client";` if you're using the App Router.

**Comment by amannn** [comment] 2023-11-27 15:55
Ok, let's close this issue then. Thank you for posting your findings!

To follow up here again this would require further analysis on the root cause and an isolated reproduction in order to make this actionable for Sentry or `next-intl`.

**Closed by amannn** 2023-11-27 15:55 UTC
Labels: bug, unconfirmed

**Comment by ixartz** [comment] 2023-12-18 22:22
I got the same error with Sentry, I try the fix with the not-found file: https://github.com/ixartz/my-app-sentry/blob/main/src/app/%5Blocale%5D/not-found.tsx
But, I still get the error.

It's a new Next.js project starting from scratch. Without `next-intl`, I didn't get any error. After adding `next-intl`, I'm starting to see the error on my local environment.

**Comment by lforst** [comment] 2023-12-19 08:30
Sentry maintainer here. I think we somehow need to ignore these errors inside the Sentry SDK. They are a react mechanism and used for control flow (e.g. throwing promises is used for suspense).

**Comment by ovflowd** [comment] 2023-12-19 10:25
> Sentry maintainer here. I think we somehow need to ignore these errors inside the Sentry SDK. They are a react mechanism and used for control flow (e.g. throwing promises is used for suspense).

What I wonder, Luca, is. If these are being thrown inside react itself, is it due to something being done erroneously?

**Comment by lforst** [comment] 2023-12-19 10:32
> > Sentry maintainer here. I think we somehow need to ignore these errors inside the Sentry SDK. They are a react mechanism and used for control flow (e.g. throwing promises is used for suspense).
> 
> What I wonder, Luca, is. If these are being thrown inside react itself, is it due to something being done erroneously?

I honestly don't think so. I know way too little about RSCs yet (as probably everybody else) to make a 100% call on this but I would say that this is just how React works now with Suspense boundaries and we need to work around it.

I can imagine that by turning certain components into client components you disabled the mechanism that throws this "Error".

**Comment by kevupton** [comment] 2024-04-15 10:46
I am still getting this error as well, how come this issue has been closed. This definitely is something that needs to be fixed 🙏
