### ISSUE TITLE
Support `localePrefix` setting per domain

### ISSUE THREAD

**Issue by markoleavy** [amannn/next-intl#1055] opened 2024-05-06 16:55 UTC
### Is your feature request related to a problem? Please describe.

It would be really useful being able to configure a `localePrefix` preference per domain, in the domain config objects.

### Describe the solution you'd like

Being able to declare a prop inside the domain object and that overrides the default behavior would fix this issue.
```js
export default createMiddleware({
  defaultLocale: 'en-US',
  locales: ['en-US', 'fr-FR', 'en-GB', 'de-DE', 'it-IT']
  domains: [
    {
      domain: 'www.mywebsite.it',
      defaultLocale: 'it-IT',
      localePrefix: 'as-needed',
      locales: ['it-IT']
    },
    {
      domain: 'www.mywebsite.com',
      defaultLocale: 'en-US',
      localePrefix: 'always',
      locales: ['en-US', 'fr-FR', 'en-GB', 'de-DE']
    }
  ]
});
```

### Describe alternatives you've considered

As explained in discussion #1030, at the moment is possible to use an empty string as default locale to get kind of a "always" behavior while "as-needed" is selected in main config.
This is not a documented feature, and might break in the future.

See also: https://github.com/amannn/next-intl/issues/1055#issuecomment-2147830453

**Comment by amannn** [comment] 2024-06-04 14:51
Prefixes can also be customized with https://github.com/amannn/next-intl/issues/653, this should be taken into account when this is being worked on.

**Comment by amannn** [comment] 2024-06-04 15:31
As a side note, this can currently be realized by running a separate build for each domain and providing a different config for `localePrefix` e.g. based on an environment parameter.

**Comment by george-roussos** [comment] 2024-07-17 05:39
Hi, I am trying to use this workaround for the time being, but I am having no luck. Specifically, we have some domains that do not have a locale prefix and a general domain which routes based on prefixes. So I tried something like:

```
export const domains: DomainsConfig<(typeof locales)["en-GB"]> = [
  {
    domain: "test.domain.it",
    defaultLocale: "" as "it-IT",
    locales: ["it-IT"],
  },
  {
    domain: "test.domain.fr",
    defaultLocale: "" as "fr-FR",
    locales: ["fr-FR"],
  },
}

export const navigation: any = {
  locales: locales["en"],
  pathnames,
  localePrefix: "as-needed",
};
```

The `domains` array only includes the special domains. Am I doing something wrong?

**Comment by amannn** [comment] 2024-10-01 17:45
While working on https://github.com/amannn/next-intl/pull/1316, I realized that setting a different `localePrefix` per domain is unfortunately not really possible while keeping the ability to render pages statically. Due to this, I think the solution really is to have separate builds for each domain if you have this requirement.

I've now addressed this in a section here: [Can I use a different `localePrefix` setting per domain?](https://next-intl-docs-git-canary-next-intl.vercel.app/docs/routing#domains-localeprefix-individual)

This note is currently included in a prerelease of the docs and will be released as part of https://github.com/amannn/next-intl/pull/1391.

---

@george-roussos It looks like you might be looking for `localePrefix: 'never'`?

**Comment by AdamQuadmon** [comment] 2024-10-04 11:46
> Due to this, I think the solution really is to have separate builds for each domain if you have this requirement.

should we use _App Router setup without i18n routing_ to work with separate builds?

**Comment by amannn** [comment] 2024-10-04 12:40
@AdamQuadmon Sorry, I don't quite understand your question. The discussion in this issue is about having a different `localePrefix` per domain. If there's a locale prefix, you'll use the setup _with_ i18n routing. See also the section I've linked to in my comment above.

**Comment by AdamQuadmon** [comment] 2024-10-04 13:16
> Sorry, I don't quite understand your question.

Sorry, I'm mixing up different topics and making confusion.

Initially I was investigating why `localePrefix: 'never'` was not respected in my configuration with different domains.

Reading this last comment of yours I thought that having separate builds were a better solution for SEO and other routing issues.

So I thought I could mix the two solutions: separate builds with no routing for dedicated SEO domains and routing solution for a catch all domain.

The scenario is

- example.com - builds only english for seo
- it.example.com - builds only italian for seo
- app.example.com - builds all the languages for the app

maybe [nextjs multi-zones](https://nextjs.org/docs/app/building-your-application/deploying/multi-zones) can separate better the SEO from the APP?

**Comment by amannn** [comment] 2024-10-04 13:22
> Initially I was investigating why `localePrefix: 'never'` was not respected in my configuration with different domains.

Hmm, not sure either—feel free to open an issue if you have a minimal reproduction!

But yes, building the app separately by domain and using the setup without i18n routing is definitely also an option for your case!

**Closed** 2024-10-21 14:16 UTC
Labels: enhancement, contributions welcome, has-workaround, area: routing
