### ISSUE TITLE
Next-intl with next-auth

### ISSUE THREAD

**Issue by bilel-lm** [amannn/next-intl#258] opened 2023-04-27 17:58 UTC
### Description

Hey

I followed the [(doc)](https://next-intl-docs.vercel.app/docs/next-13/client-components) to add the translations to my nextJS app however it doesn't work, I have this error when landing on the home page

I'm using NextJS v13.3.0 (with /app folder)
Here is my middleware

```tsx
import withAuth from "next-auth/middleware";
import createMiddleware from "next-intl/middleware";

const locales = ["en", "fr"];
const publicPages = ["login"];
const whitelist = RegExp(
  `^(\\/(${locales.join("|")})\\/)?(${publicPages.join("|")})$`,
  "i"
);

const intlMiddleware = createMiddleware({
  locales: locales,
  defaultLocale: "en",
});

export default withAuth(intlMiddleware, {
  pages: {
    signIn: "/login",
  },
  callbacks: {
    authorized: ({ req, token }) =>
      whitelist.test(req.nextUrl.pathname) || !!token,
  },
});

export const config = {
  matcher: ["/((?!api/auth|_next|favicon.ico).*)"],
};
```

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

Private app

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

<img width="992" alt="Capture d’écran 2023-04-27 à 19 52 42" src="https://user-images.githubusercontent.com/27872245/234951600-87266517-c5e7-4bc7-9be4-c09616b04966.png">

**Comment by amannn** [comment] 2023-04-28 07:22
Hey! This seems to be a duplicate of #247. I hope to find some time today to look into this, feel free to follow along on the linked issue!

**Closed by amannn** 2023-04-28 07:22 UTC
Labels: bug, unconfirmed

**Comment by mdtausifiqbal** [comment] 2023-10-10 16:17
I am setting up /login and /signup as public pages but unfortunately it doesn't secure home page i.e ("/")

**Comment by mdtausifiqbal** [comment] 2023-10-10 16:19
![image](https://github.com/amannn/next-intl/assets/33699526/e6ad4f0f-285a-42a3-b73c-dd051209c23c)
