### ISSUE TITLE
not working with nextjs 14

### ISSUE THREAD

**Issue by mh-nikbakht** [amannn/next-intl#592] opened 2023-11-02 05:19 UTC
### Is your feature request related to a problem? Please describe.

its not compatible with next v14 it can just install with --force in npm

### Describe the solution you'd like

make compatible with nextjs14 and app router . Today’s app router is more than page . 

### Describe alternatives you've considered

just compatible it

**Comment by shareef99** [comment] 2023-11-02 05:53
Can you show the error message?
Try this #584

**Comment by amannn** [comment] 2023-11-02 18:43
Duplicate of #584, please see https://github.com/amannn/next-intl/issues/584#issuecomment-1791334022

**Closed by amannn** 2023-11-02 18:43 UTC
Labels: enhancement, unconfirmed
