### ISSUE TITLE
Allow t() to return falsy result instead of translation key or provide a way to add a fallback value

### ISSUE THREAD

**Issue by wscourge** [amannn/next-intl#580] opened 2023-10-26 02:51 UTC
### Is your feature request related to a problem? Please describe.

For Next.js 13 Metadata, I want to do the following:

```
export async function generateMetadata({ params: { locale }) {
  const t = await getTranslator(locale, "home")

  return {
    title: t("title"),
    openGraph: {
      title: t("seo.og.title") || t("seo.title") || t("title"),
    }
  }
}
```

### Describe the solution you'd like

Either will do:

1. `t.optional('home')` that'd to return `""` or other fals-y value. Similar to `t.rich()`.
2. `t('seo.og.title', null, t('seo.title', null, t('title')))`, where the 3rd arguments is a fallback value.

### Describe alternatives you've considered

As of now, I'm doing it with my customized version of the `t()` function:

```
export const t = async (locale: Locale, at: string, paths: Array<string>) => {
  const t = await getTranslator(locale, at)
  return t(paths.find((path: string) => !t(path).startsWith(`${at}.`)))
}

// usage
t(locale, "home", ["seo.og.title", "seo.title", "title"])
```

It works, but results in the pretty annoying, irrelevant error:

> IntlError: MISSING_MESSAGE: Could not resolve `seo.og.title` in `site.home`.
>     at getFallbackFromErrorAndNotify (webpack-internal:///(rsc)/./node_modules/use-intl/dist/development/createIntl-dfba4462.js:131:23)
>     at translateBaseFn (webpack-internal:///(rsc)/./node_modules/use-intl/dist/development/createIntl-dfba4462.js:153:20)
>     at translateFn (webpack-internal:///(rsc)/./node_modules/use-intl/dist/development/createIntl-dfba4462.js:222:24)
>     at base (webpack-internal:///(rsc)/./node_modules/use-intl/dist/development/core.js:24:16)
>     at eval (webpack-internal:///(rsc)/./lib/i18n.ts:26:34)
>     at Array.find (<anonymous>)
>     at t (webpack-internal:///(rsc)/./lib/i18n.ts:26:20)
>     at async Promise.all (index 4)
>     at async localizedPageMetadata (webpack-internal:///(rsc)/./lib/seo.ts:44:82) {
>  code: 'MISSING_MESSAGE',
>  originalMessage: 'Could not resolve `seo.tw.title` in `site.home`.'
> }

**Comment by amannn** [comment] 2023-10-26 07:49
Thanks for the request, this seems to be a duplicate of https://github.com/amannn/next-intl/issues/88. I'll close this ticket in favor of the existing one.

**Closed by amannn** 2023-10-26 07:49 UTC
Labels: enhancement, unconfirmed

**Comment by wscourge** [comment] 2023-10-26 08:23
Sure, sorry for the dupe

**Comment by wscourge** [comment] 2023-10-26 09:29
Is there currently a way to suppress the error tho?

**Comment by amannn** [comment] 2023-10-26 10:02
Yep, please see the alternatives section in the linked issue.
