### ISSUE TITLE
behind a proxy getAlternateLinksHeaderValue dont play well

### ISSUE THREAD

**Issue by joacub** [amannn/next-intl#403] opened 2023-07-13 17:34 UTC
### Description

when yo uare behind a proxy using the alternate links will thorw the wrong urls

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

no response

### Reproduction description

using behind a proxy

### Expected behaviour

url to match the real hostnames

**Comment by amannn** [comment] 2023-07-14 07:52
I hope you understand that this bug report is incomplete, misses the mandatory reproduction and doesn't provide any relevant details about what exactly the issue is.

I'll close this for the time being, as it's not actionable. Feel free to open a new issue, but make sure to include all relevant details (e.g. a curl example, showing which response headers you receive, what the expected response is, etc.).

**Closed by amannn** 2023-07-14 07:52 UTC
Labels: bug, unconfirmed
