### ISSUE TITLE
next_intl__WEBPACK_IMPORTED_MODULE_1__.useFormatter) is not a function

### ISSUE THREAD

**Issue by opendeluxe** [amannn/next-intl#413] opened 2023-07-20 19:00 UTC
### Description

When following the docs and example code for `useFormatter`, I get the following error:

> Unhandled Runtime Error Error: (0 , next_intl__WEBPACK_IMPORTED_MODULE_1__.useFormatter) is not a function

```
import { useFormatter } from 'next-intl';

export default async function BlogComponent({ blog,}: { blog: Blog; }) {
  const format = useFormatter();

  const dt = format.dateTime(blog.pubDate, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });

  return <div>...</div>
}
```

package.json:

```
  "dependencies": {
    "@types/node": "20.4.2",
    "@types/react": "18.2.15",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.14",
    "eslint": "8.45.0",
    "eslint-config-next": "13.4.10",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^5.0.0",
    "next": "13.4.10",
    "next-intl": "^2.19.0",
    "postcss": "8.4.26",
    "prettier": "^3.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.3",
    "typescript": "5.1.6"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^6.1.0"
  }
}
```

### Mandatory reproduction URL (CodeSandbox or GitHub repository)

https://next-intl-docs.vercel.app/docs/usage/dates-times

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on …
3. See error: … 

### Expected behaviour

It would work as written in the docs.

**Comment by amannn** [comment] 2023-07-24 05:10
I'll have to close this since the mandatory reproduction is missing, I hope you understand.

**Closed by amannn** 2023-07-24 05:10 UTC
Labels: bug, unconfirmed
