### ISSUE TITLE
Navigates to a white page

### ISSUE THREAD

**Issue by bitttttten** [amannn/next-intl#887] opened 2024-02-26 13:34 UTC
### Description

We have 2 routes, and when navigating between them the page just goes blank. You have to refresh to see the content.

We are using the app router, with dynamic rendering, and next-intl.

Our page:

```tsx
// app/[locale]/a/b/page.tsx
import type { Metadata } from 'next'
import { useTranslations } from 'next-intl'
import { getTranslations, unstable_setRequestLocale } from 'next-intl/server'

import OGImage from '@/assets/pages/og-image.png'

export const dynamic = 'force-dynamic'

type Params = {
  locale: string
}

export async function generateMetadata({
  params: { locale },
}: {
  params: Params
}): Promise<Metadata> {
  const t = await getTranslations({ locale, namespace: 'pages' })

  return {
    metadataBase: new URL('https://www.my-url.com/'),
    title: t('title'),
    description: t('description'),
    openGraph: {
      images: [OGImage.src],
    },
  }
}

export default function B({ params: { locale } }: { params: Params }) {
  unstable_setRequestLocale(locale)

  const t = useTranslations('pages')
  return (
    <>
      <div data-test={t('test')} />
    </>
  )
}
```

With this setup if you navigate from /a/ to /a/b/, a white page will appear.

### Mandatory reproduction URL

https://github.com/bitttttten/white-page-navigation-bug
https://white-page-navigation-bug.vercel.app/en

### Reproduction description

Steps to reproduce:
1. go to /en/a
2. click on link to page b
3. see white page

### Expected behaviour

Steps to reproduce:
1. go to /en/a
2. click on link to page b
3. see page b

**Comment by amannn** [comment] 2024-02-26 15:42
I can't reproduce the issue unfortunately:


https://github.com/amannn/next-intl/assets/4038316/4a0adc99-2096-4117-8128-02d496b696b7

**Comment by vordgi** [comment] 2024-03-24 17:37
@amannn There is a peculiarity with client-server components. Inside the client component is an asynchronous RSC. Sometimes it works, sometimes it doesn't. And when it doesn't work - an error throws (_which was mistaken for a white screen_).

How to reproduce:

Go to the page http://localhost:3000/en/a/, go to http://localhost:3000/en/a/b/, reload the page, press "back" in the browser panel, press "forward".

I think it's worth closing, there is no bug)

![image](https://github.com/amannn/next-intl/assets/91429106/99cd5bae-cb7b-41a4-a6e8-bb953e6ffe98)

**Closed** 2024-03-25 09:58 UTC
Labels: bug, unconfirmed
